export const allCars = [
    {
        manufacturer: "VW",
        year: 2008,
        fuel: "2.5",
        limit: 10,
        model: "Polo",
        city_mpg: 30,
        class: "",
        combination_mpg: 45,
        cylinders: 30,
        displacement: 26,
        drive: "",
        fuel_type: "",
        highway_mpg: 50,
        make: "",
        transmission: "",
        message: ""
    },
    {
        manufacturer: "BMW",
        year: 2008,
        fuel: "2.5",
        limit: 10,
        model: "Polo",
        city_mpg: 30,
        class: "",
        combination_mpg: 45,
        cylinders: 30,
        displacement: 26,
        drive: "",
        fuel_type: "",
        highway_mpg: 50,
        make: "",
        transmission: "",
        message: ""
    },
    {
        manufacturer: "Benz",
        year: 2008,
        fuel: "2.5",
        limit: 10,
        model: "Polo",
        city_mpg: 30,
        class: "",
        combination_mpg: 45,
        cylinders: 30,
        displacement: 26,
        drive: "",
        fuel_type: "",
        highway_mpg: 50,
        make: "",
        transmission: "",
        message: ""
    },
]